version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=hydroDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  backend:
    build: .
    command: bash -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db