# Generated by Django 4.2.11 on 2024-03-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydrosystem',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
